import type { Match, League, Sport } from './types'

export const sports: Sport[] = [
  { id: 'football', name: 'Football', icon: '⚽', matchCount: 124 },
  { id: 'basketball', name: 'Basketball', icon: '🏀', matchCount: 32 },
  { id: 'tennis', name: 'Tennis', icon: '🎾', matchCount: 18 },
  { id: 'baseball', name: 'Baseball', icon: '⚾', matchCount: 12 },
  { id: 'hockey', name: 'Hockey', icon: '🏒', matchCount: 8 },
  { id: 'volleyball', name: 'Volleyball', icon: '🏐', matchCount: 6 },
]

export const leagues: League[] = [
  { id: 'champions-league', name: 'Champions League', country: 'Europe', flag: '🏆', matchCount: 4 },
  { id: 'premier-league', name: 'Premier League', country: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', matchCount: 10 },
  { id: 'la-liga', name: 'La Liga', country: 'Spain', flag: '🇪🇸', matchCount: 12 },
  { id: 'serie-a', name: 'Serie A', country: 'Italy', flag: '🇮🇹', matchCount: 8 },
  { id: 'bundesliga', name: 'Bundesliga', country: 'Germany', flag: '🇩🇪', matchCount: 9 },
  { id: 'ligue-1', name: 'Ligue 1', country: 'France', flag: '🇫🇷', matchCount: 10 },
]

export const countries = [
  { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺' },
  { code: 'AT', name: 'Austria', flag: '🇦🇹' },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱' },
  { code: 'CN', name: 'China', flag: '🇨🇳' },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰' },
  { code: 'GB-ENG', name: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { code: 'FI', name: 'Finland', flag: '🇫🇮' },
  { code: 'FR', name: 'France', flag: '🇫🇷' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪' },
  { code: 'GR', name: 'Greece', flag: '🇬🇷' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽' },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱' },
  { code: 'NO', name: 'Norway', flag: '🇳🇴' },
  { code: 'PL', name: 'Poland', flag: '🇵🇱' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭' },
  { code: 'US', name: 'USA', flag: '🇺🇸' },
]

export const liveMatches: Match[] = [
  {
    id: 'live-1',
    league: 'Champions League',
    country: 'Europe',
    homeTeam: 'Paris Saint Germain',
    awayTeam: 'Arsenal',
    homeScore: 1,
    awayScore: 1,
    minute: "67'",
    isLive: true,
    odds: { home: 2.36, draw: 3.50, away: 3.35 },
  },
  {
    id: 'live-2',
    league: 'Premier League',
    country: 'England',
    homeTeam: 'Manchester City',
    awayTeam: 'Liverpool',
    homeScore: 2,
    awayScore: 1,
    minute: "54'",
    isLive: true,
    odds: { home: 1.85, draw: 3.80, away: 4.20 },
  },
  {
    id: 'live-3',
    league: 'La Liga',
    country: 'Spain',
    homeTeam: 'Real Madrid',
    awayTeam: 'Barcelona',
    homeScore: 0,
    awayScore: 0,
    minute: "23'",
    isLive: true,
    odds: { home: 2.10, draw: 3.40, away: 3.50 },
  },
  {
    id: 'live-4',
    league: 'Serie A',
    country: 'Italy',
    homeTeam: 'AC Milan',
    awayTeam: 'Inter Milan',
    homeScore: 1,
    awayScore: 2,
    minute: "78'",
    isLive: true,
    odds: { home: 4.50, draw: 4.00, away: 1.75 },
  },
]

export const upcomingMatches: Match[] = [
  {
    id: 'upcoming-1',
    league: 'Champions League',
    country: 'Europe',
    homeTeam: 'Bayern Munich',
    awayTeam: 'Juventus',
    startTime: '19:00',
    isLive: false,
    odds: { home: 1.90, draw: 3.60, away: 4.20 },
  },
  {
    id: 'upcoming-2',
    league: 'Premier League',
    country: 'England',
    homeTeam: 'Chelsea',
    awayTeam: 'Tottenham',
    startTime: '17:30',
    isLive: false,
    odds: { home: 2.25, draw: 3.40, away: 3.20 },
  },
  {
    id: 'upcoming-3',
    league: 'La Liga',
    country: 'Spain',
    homeTeam: 'Atletico Madrid',
    awayTeam: 'Sevilla',
    startTime: '21:00',
    isLive: false,
    odds: { home: 1.75, draw: 3.80, away: 4.80 },
  },
  {
    id: 'upcoming-4',
    league: 'Bundesliga',
    country: 'Germany',
    homeTeam: 'Borussia Dortmund',
    awayTeam: 'RB Leipzig',
    startTime: '18:30',
    isLive: false,
    odds: { home: 2.05, draw: 3.50, away: 3.60 },
  },
  {
    id: 'upcoming-5',
    league: 'Ligue 1',
    country: 'France',
    homeTeam: 'Lyon',
    awayTeam: 'Monaco',
    startTime: '20:00',
    isLive: false,
    odds: { home: 2.40, draw: 3.30, away: 3.00 },
  },
  {
    id: 'upcoming-6',
    league: 'Serie A',
    country: 'Italy',
    homeTeam: 'Napoli',
    awayTeam: 'Roma',
    startTime: '15:00',
    isLive: false,
    odds: { home: 1.95, draw: 3.55, away: 4.00 },
  },
]

// Extended matches by sport
export const footballMatches: Match[] = [
  ...liveMatches,
  ...upcomingMatches,
  {
    id: 'football-7',
    league: 'Premier League',
    country: 'England',
    homeTeam: 'Arsenal',
    awayTeam: 'Manchester United',
    startTime: '14:00',
    isLive: false,
    odds: { home: 2.10, draw: 3.40, away: 3.60 },
  },
  {
    id: 'football-8',
    league: 'Premier League',
    country: 'England',
    homeTeam: 'Newcastle',
    awayTeam: 'Brighton',
    startTime: '16:30',
    isLive: false,
    odds: { home: 1.95, draw: 3.50, away: 4.00 },
  },
  {
    id: 'football-9',
    league: 'La Liga',
    country: 'Spain',
    homeTeam: 'Valencia',
    awayTeam: 'Villarreal',
    homeScore: 0,
    awayScore: 1,
    minute: "35'",
    isLive: true,
    odds: { home: 3.20, draw: 3.30, away: 2.25 },
  },
  {
    id: 'football-10',
    league: 'Bundesliga',
    country: 'Germany',
    homeTeam: 'Bayern Munich',
    awayTeam: 'Wolfsburg',
    startTime: '15:30',
    isLive: false,
    odds: { home: 1.25, draw: 6.00, away: 11.00 },
  },
]

export const basketballMatches: Match[] = [
  {
    id: 'basketball-1',
    league: 'NBA',
    country: 'USA',
    homeTeam: 'LA Lakers',
    awayTeam: 'Golden State Warriors',
    homeScore: 87,
    awayScore: 92,
    minute: 'Q4',
    isLive: true,
    odds: { home: 2.50, draw: 15.00, away: 1.60 },
  },
  {
    id: 'basketball-2',
    league: 'NBA',
    country: 'USA',
    homeTeam: 'Boston Celtics',
    awayTeam: 'Miami Heat',
    startTime: '01:00',
    isLive: false,
    odds: { home: 1.45, draw: 12.00, away: 2.90 },
  },
  {
    id: 'basketball-3',
    league: 'EuroLeague',
    country: 'Europe',
    homeTeam: 'Real Madrid',
    awayTeam: 'Barcelona',
    startTime: '20:00',
    isLive: false,
    odds: { home: 1.75, draw: 14.00, away: 2.10 },
  },
  {
    id: 'basketball-4',
    league: 'EuroLeague',
    country: 'Europe',
    homeTeam: 'Olympiacos',
    awayTeam: 'Panathinaikos',
    homeScore: 45,
    awayScore: 48,
    minute: 'HT',
    isLive: true,
    odds: { home: 1.90, draw: 13.00, away: 1.95 },
  },
]

export const tennisMatches: Match[] = [
  {
    id: 'tennis-1',
    league: 'ATP Tour',
    country: 'USA',
    homeTeam: 'C. Alcaraz',
    awayTeam: 'N. Djokovic',
    homeScore: 2,
    awayScore: 1,
    minute: '3rd Set',
    isLive: true,
    odds: { home: 1.65, draw: 0, away: 2.30 },
  },
  {
    id: 'tennis-2',
    league: 'WTA Tour',
    country: 'France',
    homeTeam: 'I. Swiatek',
    awayTeam: 'A. Sabalenka',
    startTime: '14:30',
    isLive: false,
    odds: { home: 1.80, draw: 0, away: 2.05 },
  },
  {
    id: 'tennis-3',
    league: 'ATP Tour',
    country: 'Australia',
    homeTeam: 'J. Sinner',
    awayTeam: 'D. Medvedev',
    startTime: '09:00',
    isLive: false,
    odds: { home: 1.55, draw: 0, away: 2.50 },
  },
]

export const hockeyMatches: Match[] = [
  {
    id: 'hockey-1',
    league: 'NHL',
    country: 'USA',
    homeTeam: 'Toronto Maple Leafs',
    awayTeam: 'Montreal Canadiens',
    homeScore: 2,
    awayScore: 3,
    minute: '2nd Period',
    isLive: true,
    odds: { home: 2.20, draw: 4.50, away: 1.80 },
  },
  {
    id: 'hockey-2',
    league: 'NHL',
    country: 'USA',
    homeTeam: 'NY Rangers',
    awayTeam: 'Boston Bruins',
    startTime: '02:00',
    isLive: false,
    odds: { home: 2.05, draw: 4.00, away: 1.90 },
  },
]

// All sports data
export const allSportsData = {
  football: footballMatches,
  basketball: basketballMatches,
  tennis: tennisMatches,
  hockey: hockeyMatches,
  baseball: upcomingMatches.slice(0, 2),
  volleyball: upcomingMatches.slice(2, 4),
}
